output_list <- function(obs_r, act_r,
                        critical_r, r_final, rxcv, rycv, rxcvGz, rycvGz, 
                        itcvGz, itcv, r2xz, r2yz, benchmark_corr_product = NA, itcv_ratio_to_benchmark = NA,
                        delta_star, delta_star_restricted, delta_exact, delta_pctbias, 
                        cor_oster, cor_exact, 
                        beta_threshold, beta_threshold_verify,
                        perc_bias_to_change, 
                        RIR_primary, RIR_supplemental, RIR_perc, 
                        fragility_primary, fragility_supplemental,
                        starting_table, final_table, 
                        user_SE, analysis_SE,
                        needtworows, 
                        Fig_ITCV, Fig_RIR,
                        cond_RIRpi_null, cond_RIRpi_fixedY, cond_RIRpi_rxyz,
                        cond_RIR_null, cond_RIR_fixedY, cond_RIR_rxyz,
                        est_eff = NA, user_std_err = NA, p_start = NA,
                        est_eff_final = NA, std_err_final = NA, p_final = NA,
                        p_destination = NA, p_destination_extra = NA,
                        total_RIR = NA, total_switch = NA,
                        table_start_3x3 = NA, table_final_3x3 = NA,
                        fisher_ob = NA, chisq_ob = NA, 
                        fisher_final = NA, chisq_final = NA
                        ) {
  result <- list(obs_r = obs_r,
                 act_r = act_r, 
                 critical_r = critical_r, 
                 r_final = r_final,
                 rxcv = rxcv, 
                 rycv = rycv, 
                 rxcvGz = rxcvGz, 
                 rycvGz = rycvGz, 
                 itcvGz = itcvGz, 
                 itcv = itcv, 
                 r2xz = r2xz, 
                 r2yz = r2yz, 
                 benchmark_corr_product = benchmark_corr_product,
                 itcv_ratio_to_benchmark = itcv_ratio_to_benchmark,
                 delta_star = delta_star, 
                 delta_star_restricted = delta_star_restricted, 
                 delta_exact = delta_exact, 
                 delta_pctbias = delta_pctbias, 
                 cor_oster = cor_oster, 
                 cor_exact = cor_exact, 
                 beta_threshold = beta_threshold, 
                 beta_threshold_verify = beta_threshold_verify,
                 perc_bias_to_change = perc_bias_to_change, 
                 RIR_primary = RIR_primary, 
                 RIR_supplemental = RIR_supplemental, 
                 RIR_perc = RIR_perc, 
                 fragility_primary = fragility_primary, 
                 fragility_supplemental = fragility_supplemental, 
                 starting_table = starting_table, 
                 final_table = final_table, 
                 user_SE = user_SE,
                 analysis_SE = analysis_SE, 
                 needtworows = needtworows,
                 Fig_ITCV = Fig_ITCV,
                 Fig_RIR = Fig_RIR,
                 cond_RIRpi_null = cond_RIRpi_null, 
                 cond_RIRpi_fixedY = cond_RIRpi_fixedY, 
                 cond_RIRpi_rxyz = cond_RIRpi_rxyz,
                 cond_RIR_null = cond_RIR_null, 
                 cond_RIR_fixedY = cond_RIR_fixedY, 
                 cond_RIR_rxyz = cond_RIR_rxyz,
                 est_eff = est_eff, user_std_err = user_std_err, p_start = p_start,
                 est_eff_final = est_eff_final, std_err_final = std_err_final, p_final = p_final,
                 p_destination = p_destination, p_destination_extra = p_destination_extra,
                 total_RIR = total_RIR, total_switch = total_switch,
                 table_start_3x3 = table_start_3x3, table_final_3x3 = table_final_3x3,
                 fisher_ob = fisher_ob, chisq_ob = chisq_ob, 
                 fisher_final = fisher_final, chisq_final = chisq_final
                 )
  result <- result[!is.na(result)]
  message("For interpretation, check out to_return = 'print'.")
  return(result)
}
